version: "3.9"
services:
  mysql:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 1234!@#$
    ports:
      - "3306:3306"
